### ISSUE TITLE
Can we get an an installable release of this branch?

### ISSUE THREAD

**Issue by gajewsk2** [jakeprobst/Anki-Android#2]
Finding the load balancer really useful, and hoping we can have a release in the release tabs, seems there hasn't been one in a while. Saw the readme said to just make an issue if we wanted this fork updated, so here I am. :)

**Comment by jakeprobst** [comment]
https://github.com/jakeprobst/Anki-Android/releases/tag/2017-08-09

enjoy

**Comment by gajewsk2** [comment]
My hero! Are there any settings like desktop for the load balancer? Just opened the app, but i'm not seeing any indication of the load balancer at work.

**Comment by jakeprobst** [comment]
loadbalancer settings get synced so ankidroid will use the same settings as you have on the desktop.

At one point I made a proper interface for modifiying the settings back when I tried to get it merged properly, but it has been lost to the git void.

**Comment by gajewsk2** [comment]
Works for me. Thanks for addressing it.

2017/08/09 午後9:58 "Jake Probst" <notifications@github.com>:

**Comment by gajewsk2** [comment]
Sorry to have to ask, but could you release a version based on a stable version of anki? I'm getting weird issues and crashes that weren't present on https://github.com/ankidroid/Anki-Android/releases/tag/v2.8.2 .
Pretty sure they're related to the ankidroid teams changes: things like the code editor blowing up and images max-width being broken. #3612
