### ISSUE TITLE
Stable version of ankidroid released. Update for load balancer? 

### ISSUE THREAD

**Issue by gajewsk2** [jakeprobst/Anki-Android#3]
I've been using the last apk release if this fork, so thank you. The last release that was do for this repo was off of an alpha version, and has some issues with images. Now that a stable version of ankidroid has been released, can we get an apk of 2.8.3 for this repo released?

**Comment by jakeprobst** [comment]
https://github.com/jakeprobst/Anki-Android/releases/tag/v2.8.3-loadbalancer
enjoy
